// <auto-generated />
namespace Selama.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ForumSectionTitleLenIncrease_Testing : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ForumSectionTitleLenIncrease_Testing));
        
        string IMigrationMetadata.Id
        {
            get { return "201605240354396_ForumSectionTitleLenIncrease_Testing"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
